version: '3'
services:
  api:
    build:
      context: .
      dockerfile: json_server/containers/Dockerfile
    ports:
      - "8032:3000"
    volumes:
      - ./json_server:/app
  spa:
    build:
      context: .
      dockerfile: spa/containers/Dockerfile
    ports:
      - "8031:3000"
    volumes:
      - ./spa:/app
      - /app/node_modules
