version: '3'
services:
  api:
    build:
      context: .
      dockerfile: json_server/containers/Dockerfile
    ports:
      - "${API_PORT-:8032}:3000"
    volumes:
      - ./json_server:/app
  spa:
    build:
      context: .
      dockerfile: spa/containers/Dockerfile
    environment:
      - WDS_SOCKET_PORT=${SPA_PORT:-8031}
    ports:
      - ${SPA_PORT:-8031}:3000
    volumes:
      - ./spa:/app
      - /app/node_modules
